### PR TITLE
Fully Rounded Buttons, Darker Start Screen Background and Rounded Ads

### PR DESCRIPTION
**Pull request by JanluOfficial**
Inspired by JanluUI 23 (my WIP UI Kit for CSS), Buttons are now fully rounded, with no border, and they expand on hover. The Ads are also now rounded, aswell as the background being darker.

Should hopefully break nothing... Hopefully. 😅

### CODE REVIEW

**Comment by FiniteSingularity** [comment]
Hi @JanluOfficial,

One request.  The ads were intended to mimic early internet banner ads- e.g., square and a bit ugly.  could you push a quick update that switches back the ads to their original late-90s glory? Then I'll merge in the button change.

**Comment by JanluOfficial** [comment]
Sure thing, I will edit that right now...

**Comment by JanluOfficial** [comment]
> Hi @JanluOfficial,
> 
> One request. The ads were intended to mimic early internet banner ads- e.g., square and a bit ugly. could you push a quick update that switches back the ads to their original late-90s glory? Then I'll merge in the button change.

@FiniteSingularity I have removed the css that rounds the ads, meaning that ads are now square. At least they should be.

**Comment by JanluOfficial** [comment]
In addition to that, buttons how have a "pressed" aka active state

**Comment by JanluOfficial** [comment]
this is long ago

**Comment by FiniteSingularity** [comment]
Thanks for the PR @JanluOfficial.  Sorry this took so long.  Somehow this repo wasn't on my list of notifications, and I missed that you had added to the PR.

**Pull request merged**
